language: ruby
dist: xenial
os: linux
rvm:
- 2.7.1
cache:
  bundler: true
  directories:
  - "$HOME/.cache/pip"
  - assets/portfolio
branches:
  only:
  - release
env:
  global:
  - PATH=/opt/python/3.7.1/bin:$PATH
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - YAML_OVERWRITE=false
  - RESIZE_OVERWRITE=false
  - HISTOGRAM_OVERWRITE=false
  - GALLERY_RUNNER_LOG_LEVEL=DEBUG
addons:
  apt:
    packages:
    - libcurl4-openssl-dev

jobs:
  include:
  - stage: Gallery Cat crawl gallery
    before_install:
    - sudo apt update
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt --cache-dir HOME/.cache/pip
    script: python ./tools/gallery_cat.py
  - stage: HTML Proofing, Site build, deploy to master
    before_install:
    - gem install bundler
    script: "./cicd/ci_build.sh"
    deploy:
      strategy: git
      provider: pages
      local_dir: site/
      target_branch: master
      fqdn: www.pixelabs.net
      email: pixelbot@internal.pixelabs.net
      name: PixelBot
      skip_cleanup: true
      token: "$GITHUB_TOKEN"
      keep_history: true
      on:
        branch: release
notifications:
  slack:
    rooms:
      secure: kT+G4Rm6rOwVH0E67okXc1t3fxAofwxjHFjL698tMFAN0XbPPv5j87y29XMyc1fg38pjf43avKo/Nxf0Gzsr1I874uLaio92E3gowy7S7ToEsDGygwBAchNl5xSCZCAbmhq6evbFp/Y6UD7nzoTlO2QCZg0QkLMEGmSSl9DEWrxGS22zsyDRf2PaEfb9Rf5TFfcEQiT9+UA3lB6BujS6Jyr7T0Bjk2FD4MRMkentClLxX9IdPdwbYySamvfrUimNlcGVH4I8kpjBhf9G3s4T4I9HR4x9Jfj3TJ6//cP6qpoxI85DXLKlMZg0VoyZQUBjVJmW3ybTqAWkauvfBrBn7PC/ofCAh9OhJ3i6bu25JTJfyNFwJtII8Yl7UoA8pw4FaxOS4RkaKAl0kIAMZwah2P50yO0Q3VhR2aBLDU0mYAalO0wgb0v0qPJtSxvGmjnmyjyoKTQ1/m+H/H7ORarm9UNa7K6Ccw0g0SQ8sNrrUyb00EI+mFBUFsqCrZdQMZ0BK9KSvFvrREltf9N3CBIK0Do5ZVEqfkYfyM5U8wHR44v93GtQdwtklSHbrEoB7nrB8owcm71FMYXgZmVvyelE272jrF/RUL2LEO+vx4rP9VTvmbwNWsd7CaiD4KW/5U3QHjhdZg4Y31gg+ZW++zrZK9f6hNARV5rGzEYeDjV+c/g=
    on_failure: always
    on_success: always
  email: false
