language: ruby
dist: xenial
os: linux
rvm:
- 2.7.1
cache:
  bundler: true
  directories:
  - "$HOME/.cache/pip"
  - assets/portfolio
branches:
  only:
  - release
env:
  global:
  - PATH=/opt/python/3.7.1/bin:$PATH
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - YAML_OVERWRITE=false
  - RESIZE_OVERWRITE=false
  - HISTOGRAM_OVERWRITE=false
  - GALLERY_RUNNER_LOG_LEVEL=DEBUG
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
jobs:
  include:
  - stage: Gallery Cat crawl gallery
    before_install:
    - sudo apt update
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt --cache-dir HOME/.cache/pip
    script: python ./tools/gallery_cat.py
  - stage: HTML Proofing, Site build, deploy to master
    before_install:
    - gem install bundler
    script: "./cicd/ci_build.sh"
    deploy:
      strategy: git
      provider: pages
      local_dir: site/
      target_branch: master
      fqdn: www.pixelabs.net
      email: pixelbot@internal.pixelabs.net
      name: PixelBot
      skip_cleanup: true
      token: "$GITHUB_TOKEN"
      keep_history: true
      on:
        branch: release
notifications:
  slack:
    secure: a+IAHGUDs/EIkqa90LKL/KsS2g6I+IEc4HYM9s8wUAKrBkhsnneSVxzBxfxx0GWM25+WWxvvkcj3N4hJRJ5kmoggtYkNpeyHISWfIooVA5+VOuSbpimOe27xkfaxWZJDk6bG9gHd/j3gNQooLdVlliEBMFBj33rMitl1xmRdiMFw9KMvriR0UpMT0q56pRv7TYm9IBHZ/1MEauUpYrpKkYH18PLibrPlYTCi1AOHGPk0sb/SLTpsv0QS1MEkoLgjAQ/05ceH+EZPxlK1GHSLPtO7+3hnNxkGIRVNWqIsJFn5pZXqnQUlr81Wv+MlOAZF66c025Mn+eY42eJWzAnTh1wwBQ4sQaBPXM2skjvf/Dti9z5tC0R6ov2i2EJy6DYg7mVMods4Qgfhk28ZbtNE9HLfWZU+qRY+98tMy2BzEVhJriC1yJpGBcfyQ9YkuvNPEWDqbN3wgzI4PedOh6wVphJZ43ILF5fsK3m/5u5q5uR7J0r2RGP6EYdgaAXJjtoqMEhXleg6R9+nJHwTYVXCgNUMUPfqwA9+qwiHtLyGEOJzvzs0DCdgLZ9jtXR2SR0rAygmQr7Iiu618HasQBQvZ4TTEtFac01VkRjzT4+j/bNvu44FkG8PVuOukOdUA0XNS3zMeFjBc/BB4bSFMB6E42VoBOhC2sFO7PA3GG08LvY=
      on_failure: always
      on_success: change
  email: false
