language: ruby
dist: xenial
os: linux
rvm:
- 2.7.1
cache:
  bundler: true
  directories:
  - "$HOME/.cache/pip"
  - assets/portfolio
branches:
  only:
  - release
env:
  global:
  - PATH=/opt/python/3.7.1/bin:$PATH
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - YAML_OVERWRITE=false
  - RESIZE_OVERWRITE=false
  - HISTOGRAM_OVERWRITE=false
  - GALLERY_RUNNER_LOG_LEVEL=DEBUG
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
jobs:
  include:
  - stage: Gallery Cat crawl gallery
    before_install:
    - sudo apt update
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt --cache-dir HOME/.cache/pip
    script: python ./tools/gallery_cat.py
  - stage: HTML Proofing, Site build, deploy to master
    before_install:
    - gem install bundler
    script: "./cicd/ci_build.sh"
    deploy:
      strategy: git
      provider: pages
      local_dir: site/
      target_branch: master
      fqdn: www.pixelabs.net
      email: pixelbot@internal.pixelabs.net
      name: PixelBot
      skip_cleanup: true
      token: "$GITHUB_TOKEN"
      keep_history: true
      on:
        branch: release
notifications:
  slack:
    rooms:
      secure: rfbMJcGdTOjQftJvNeLRc+FYVF8P7k30ewDoSrJoc0SXRxz29yFt9eZd+7Q8LjqIZf2cvzvR2SC+kkK+fRsi4jrAiAM21o6Hw5GSriXVq/THJBGQQamWcfpEAJbo5Z2XKq6KHrS89A3xldnU0Go/AhcNLa0XpxZnsOPigjIljbZH6bjOihH4uhRyWqJGgcRgGJldyH7qOSqNXycAuvTStxfvBXr1ktQFepPYndztwIO5m/OTwgMm78CKQjOnX7gB0RI+t8q7m36P2ajabqbahJZZL7R9DxYgS8aVR2E9cN15SECrXSUUTk5cGpLTAe/muVjSs3V/rPclhYyCr5mDEG21XYJv4pD06XKY5193m2an5+cXiAaJKH2temh5SCUjb9heinix9fJovjU/x001B3QkQBT/bRfEP3BWBrQ9dDRqQcUE49vMU5uHQgSiqY+WPAlYjJfeP4FRAtD5jViSV7Bb9FbEXbIx7rFVxbgIW7AJLvS3KTcHMcodUFYW701fK/v6gEZbANTBe6xFAV/RJFgcwJskOcpdu8R8KGuyKRANzVSlteDBIx5F3hG5cy4CyERx5uSl5AAX6/X6xZZr/c+BqwsfRmQrOOGczG7skNgodBh+rGHuEcgiZFvjYLAUBckiHC7ciY8iuaMNTefy+6vrAJVYJZxuJ1TkwpIG21o=
      on_success: always
      on_failure: always
  email: false
