title: Pixelabs
email: home-inquiry@pixelabs.net
description: >- # this means to ignore newlines until "baseurl:"
  Design studio for art, technology, crafts. You can see my portfolio or buy clothing at the shop.
  A collection of art projects, digital illustrations, electronic installations, custom made accessories and more.
url: "https://www.pixelabs.net" # the base hostname & protocol for your site, e.g. http://example.com

github_username: pixelicous
twitch_username: pixelicous
soundcloud_username: pixelicous
redbubble_username: pixelicous
linkedin_username: netzerom
spotify_username: pixilicous
buymecoffee_username: pixelabs
gumroad_username: pixelabs
shop_ig_username: netz_designs
shop_fb_username: netzer.rom.designer.shop
google_analytics_id: UA-164926771-3
social_icons_enabled: true
photography_path: /assets/portfolio/photography
shop_url: "https://shop.pixelabs.net"
mail_url: "mailto:home-inquiry@pixelabs.net?subject=Pixelabs&nbsp;visitor&nbsp;question&amp;body=Hey man!"

# Build settings
# whitelist: 
  # - jekyll-analytics
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-analytics

# Jekyll Analytics Gem
# jekyll_analytics:
#   GoogleAnalytics:
#     id: UA-164926771-3   

# Jekyll 3 Pagination Gem
permalink: pretty

pagination:
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/blog/page/:date/:title' # Pages are index.html inside this folder (default)


sass:
  sass_dir: assets/css
  style: compressed
  
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  # # _portfolio
  # - scope:
  #     path: ""
  #     type: portfolio
  #   values:
  #     layout: single
  #     author_profile: false
  #     share: true

collections_dir: site_collections
collections:
  pages:
    output: true
    permalink: /:path/
  shop:
    output: true
    permalink: /:collection/:path/
  photography:
    output: true
    permalink: /portfolio/:collection/:path/
  crafts:
    output: true
    permalink: /portfolio/:collection/:path/
  digital:
    output: true
    permalink: /portfolio/:collection/:path/


# Exclude from processing.
exclude: 
  - tools/
  - cicd/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

