# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: PixeLabs homepage
email: email@domain.com
description: >- # this means to ignore newlines until "baseurl:"
  PixeLabs Homepage
url: "https://www.pixelabs.net" # the base hostname & protocol for your site, e.g. http://example.com

github_username: pixelicous
twitch_username: pixelicous
soundcloud_username: pixelicous
redbubble_username: pixelicous
spotify_username: pixilicous
buymecoffee_username: pixelabs
social_icons_enabled: true
photography_path: /assets/portfolio/photography


# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-analytics

# Jekyll Analytics Gem
jekyll_analytics:
  GoogleAnalytics:
    id: UA-164926771-2   

# Jekyll 3 Pagination Gem
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/blog/page/:num/' # Pages are index.html inside this folder (default)


sass:
  sass_dir: assets/css
  style: compressed
  
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  # # _portfolio
  # - scope:
  #     path: ""
  #     type: portfolio
  #   values:
  #     layout: single
  #     author_profile: false
  #     share: true

collections_dir: site_collections
collections:
  pages:
    output: true
    permalink: /:path/
  photography:
    output: true
    permalink: /portfolio/:collection/:path/
  crafts:
    output: true
    permalink: /portfolio/:collection/:path/
  digital:
    output: true
    permalink: /portfolio/:collection/:path/
permalink: pretty

# Exclude from processing.
exclude: 
  - tools/
  - cicd/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
