# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["release"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  prep:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Cache GalleryCat Images
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0

        with:
          path: |
            ./_data
            ./assets/portfolio/
          key: 
            ${{ runner.os }}-gallerycat-${{ env.CACHE_NUMBER }}-${{hashFiles('assets/portfolio') }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install dependencies
        run: |
          sudo apt update
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt --cache-dir "$HOME/.cache/pip"
          python3 ./tools/gallery_cat.py
          python3 ./tools/litter_cleaner.py
      - uses: actions/upload-artifact@master
        with:
          name: portfolio
          path: ./assets/portfolio/

  build:
    runs-on: ubuntu-latest
    needs: prep
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: portfolio
          path: ./assets/portfolio/
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        env:
          fqdn: www.pixelabs.net
          email: pixelbot@internal.pixelabs.net
          name: PixelBot
